#!/usr/bin/env bash
# End-to-end proof of the caller-supplied-terraform path: drives the REAL
# `prepare-custom-tf` CLI (the same command the composite action runs) against
# a fixture tool.json that declares a provider, staging the sample caller .tf
# and a generated _providers.g.tf into the platform's custom module, then runs
# `terraform init` + `terraform test` against that staged state. Always
# unstages afterward — the repo itself always ships an empty custom/ module.
#
# This is what catches a "provider declared in the manifest -> terraform init
# fails" regression (e.g. a duplicate required_providers block) that a fixture
# copied in by hand, without going through the CLI, would never exercise.
#
# The sample caller file lives at fixtures/custom/queue.tf.sample, not
# queue.tf: as a real .tf file it would be a standalone Terraform module that
# `tflint --recursive` walks into and fails to parse (it references variables
# like var.tool_name that only exist once copied next to the platform's
# custom/_context.tf). To still drive the real CLI's collect() — which only
# picks up *.tf files from the manifest's terraform.dir — stage the sample
# into a scratch app-root as queue.tf before invoking it.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
tf_dir="$(dirname "$here")"
repo_root="$(cd "$tf_dir/../.." && pwd)"
custom_dir="$tf_dir/custom"
staged_tf="$custom_dir/queue.tf"
generated_providers="$custom_dir/_providers.g.tf"

scratch_root="$(mktemp -d)"
scratch_caller_dir="$scratch_root/tests/fixtures/custom"
mkdir -p "$scratch_caller_dir"
cp "$here/fixtures/custom/queue.tf.sample" "$scratch_caller_dir/queue.tf"

# Name-agnostic cleanup: remove everything staged directly under custom/ except
# the platform-owned files, so a future fixture that stages more than one .tf
# can't leave a leftover behind for the CI job's later `tflint --recursive` step.
cleanup() {
  find "$custom_dir" -mindepth 1 -maxdepth 1 \
    ! -name "_context.tf" ! -name "_versions.tf" -exec rm -rf {} +
  rm -rf "$scratch_root"
}
trap cleanup EXIT

PYTHONPATH="$repo_root/engine" python3 -m cloudapp prepare-custom-tf \
  --tool-json "$here/fixtures/tool.custom.json" \
  --app-root "$scratch_root" \
  --custom-dir "$custom_dir"

if [ ! -f "$staged_tf" ]; then
  echo "staged custom check: expected '$staged_tf' to be staged by prepare-custom-tf" >&2
  exit 1
fi
if [ ! -f "$generated_providers" ]; then
  echo "staged custom check: expected '$generated_providers' to be generated by prepare-custom-tf" >&2
  exit 1
fi
if ! grep -q "hashicorp/random" "$generated_providers"; then
  echo "staged custom check: '$generated_providers' does not declare the fixture's random provider" >&2
  exit 1
fi

terraform -chdir="$tf_dir" init -backend=false -input=false
terraform -chdir="$tf_dir" test -filter=tests/custom.tftest.hcl

echo "staged custom check: OK ($generated_providers generated and terraform init/test both succeeded)"
